### ISSUE TITLE
Floating label not working with dynamic value

### ISSUE THREAD

**Issue by rakeshsharma0** [Cnilton/react-native-floating-label-input#93] opened 2021-09-03 12:33 UTC
Here is code of input  

 <FloatingLabelInput
            value={courseData.course_name}
            onChangeText={(val) =>
              setCourseData({ ...courseData, course_name: val })
            }
            containerStyles={styles.inputContainer}
            onFocus={() => setCourseErr("")}
            inputStyles={{
              fontFamily: "nunito-regular",
              fontSize: 15,
            }}
            customLabelStyles={{
              fontSizeFocused: 13,
              topFocused: -20,
              colorFocused: "#5130D6",
            }}
            label={"Course Name *"}
          />

![image](https://user-images.githubusercontent.com/86839613/132006103-dce0bc5e-3c06-40d0-bb1f-f398bcba6962.png)

**Comment by Cnilton** [comment] 2021-09-05 11:01
Hi @rakeshsharma0, I'll try to reproduce your issue

**Comment by rajatsj** [comment] 2021-09-08 09:01
Use timeout  to set value for label dynamically
setTimeout(
        function() {
           setName('VALUE')
        },
        1000
      );

**Comment by agencia3w** [comment] 2021-11-05 01:21
Same problem here, any solution?

**Comment by Cnilton** [comment] 2021-12-04 13:48
Hi guys, sorry for taking so long.. but unfortunately I couldn't reproduce the issue:

```javascript
<FloatingLabelInput
        label={value || 'label'}
        value={value}
        onChangeText={value => setValue(value)}
        customShowPasswordComponent={null}
        customHidePasswordComponent={null}
        hint={'hint'}
        hintTextColor="#A6A6A6"
        labelStyles={{
          backgroundColor: 'white',
          color: '#6E6E6E',
          fontFamily: 'Nunito-Regular',
        }}
        containerStyles={{
          borderWidth: 1,
          backgroundColor: '#fff',
          padding: 10,
          borderColor: '#A6A6A6',
          borderRadius: 8,
          height: 60,
          // 53
          fontFamily: 'Nunito-Regular',
          // paddingHorizontal: wp(5.2),
          color: 'black',
        }}
        inputStyles={{
          color: 'black',
          fontSize: 16,
          fontFamily: 'Nunito-Regular',
        }}
        customLabelStyles={{
          topFocused: -20,
          fontFamily: 'Nunito-Regular',
          fontSizeFocused: 13.5,
          leftFocused: -8,
          colorFocused: '#6E6E6E',
          color: '#A6A6A6',
          colorBlurred: '#6E6E6E',
        }}
        // {...restProps}
      />
```
<div>
<img src="https://user-images.githubusercontent.com/40298250/144711701-8c4ae8cf-1445-4e66-9cb2-235f8d65ea53.png" width="30%"/>
<img src="https://user-images.githubusercontent.com/40298250/144711836-d466018a-271f-4b79-9a84-a47f1a656d0e.png" width="30%"/>
<img src="https://user-images.githubusercontent.com/40298250/144711857-15f4ac64-a409-43d8-89f9-f76dd77f0d6c.png" width="30%"/>
</div>

**Comment by santiagofm** [comment] 2021-12-07 03:24
@Cnilton You can repro this when conditionally rendering the label and setting both `value` and `customLabelStyles.topFocused`:

```ts
export const Test = () => {
  const [isVisible, setVisible] = useState(false);

  useEffect(() => {
    setTimeout(() => {
      setVisible(true);
    }, 2000);
  }, []);

  return (
    <SafeAreaView>
      {isVisible && <FloatingLabelInput
        label={'Test'}
        containerStyles={inputs.containerStyles}
        inputStyles={inputs.inputStyles}
        customLabelStyles={{
          topFocused: -25,
          colorFocused: Colors.black,
          colorBlurred: Colors.gray,
          fontSizeFocused: 12,
        }}
        value={'test'}
      />}
    </SafeAreaView>
  );
}
```
If you don't set `customLabelStyles.topFocused` then it won't overlap but animate into place.

As a side question, is there any way to avoid the animation? if the label already has a value I want it to just show the label without animating. Played around with `staticLabel` but wasn't able to get it to work.

**Comment by iaminarush** [comment] 2021-12-08 06:05
@Cnilton Made a [snack](https://snack.expo.dev/@iaminarush/floating-label) to show the problem if it helps, the problem appears if the initial value is not blank, thanks for the hard work

**Comment by Abdelwahab07** [comment] 2022-02-24 13:56
Is there's any update?

**Comment by Cnilton** [comment] 2022-03-13 23:56
Hi guys, I'm sorry for taking so long. This will be fixed in the next version!

**Comment by Cnilton** [comment] 2022-03-18 16:47
New version released should fix this!

**Comment by Cnilton** [comment] 2022-03-28 21:04
@agencia3w, @santiagofm, @Abdelwahab07 and @iaminarush, can you please try the latest version?

**Closed** 2022-03-30 19:19 UTC

**Comment by BerkeAras** [comment] 2022-04-16 18:05
@Cnilton Still the same issue for me :(
