### ISSUE TITLE
cannot toggle label color on focused v1.3.4

### ISSUE THREAD

**Issue by vietcuong122** [Cnilton/react-native-floating-label-input#79] opened 2021-05-17 04:43 UTC
I have override the onFocus/onBlur props, and handled isFocused as an state variable, but the color of label when focused not changed. Here is my code, hope to get your help.
![floatinglabelinput](https://user-images.githubusercontent.com/48023195/118433381-10d44b80-b705-11eb-9e52-8b4e56ab0b24.png)

**Comment by Cnilton** [comment] 2021-05-17 22:14
Hi @vietcuong122, I'll try to reproduce this issue.

**Comment by vietcuong122** [comment] 2021-05-18 10:01
Can anyone found this issue or the solved for this?

**Comment by Cnilton** [comment] 2021-05-23 03:25
@vietcuong122, I'm sorry but using the following code I couldn't reproduce this issue.

```javascript

<FloatingLabelInput
      label={'label'}
      value={val}
      onChangeText={(newValue)=> setVal(newValue)}
      autoCapitalize={'words'}
      customLabelStyles={{colorBlurred: '#f0f', colorFocused: '#000'}}
      isFocused={focused}
      onFocus={() => { setFocused(true) }}
      onBlur={() => { setFocused(false) }}
      blurOnSubmit={false}
      />
      
     ```

**Comment by Cnilton** [comment] 2021-05-29 21:32
@vietcuong122 any updates?

**Comment by Cnilton** [comment] 2021-06-02 23:05
Closing this due to no answerq

**Closed by Cnilton** 2021-06-02 23:05 UTC
