### ISSUE TITLE
Textinput text overlap in Android Modal 

### ISSUE THREAD

**Issue by harshal311989** [Cnilton/react-native-floating-label-input#66] opened 2021-04-12 10:55 UTC
Hi team, i used thi splugin for floating effect in my textinput and i used it latest version 1.3.5 but i afce issue like when i have pre defined text in textinput it will be overlap like below screenshots

![Android](https://user-images.githubusercontent.com/75067288/114384063-dfb7a700-9bab-11eb-882b-daca888977cd.png)

My code as below 

<FloatingLabelInput
   label={textTranslation.shippingAddress.FLATNAME}
    value={flateName}
    onChangeText={(value) => {
    this.setState({ flateName: value });
      }}
      labelStyles={{
      fontFamily: globals.ProximaNovaRegular,
      color: colors.darkWarmGrey,
        }}
      />

Any idea how i can solve it?

**Comment by Cnilton** [comment] 2021-04-14 12:41
Hi @harshal311989, thanks for using this lib, and already giving the code for reproducibility. I'll test this and answer later, ok?

**Comment by harshal311989** [comment] 2021-04-14 14:00
Ok @Cnilton

**Comment by Cnilton** [comment] 2021-04-17 13:49
@harshal311989, sorry, but I couldn't reproduce your issue. Are you sure the code you provided is enough to reproduce this?

![evidencia](https://user-images.githubusercontent.com/40298250/115115341-5f59c300-9f6a-11eb-8901-bfc979713736.png)

![evidencia2](https://user-images.githubusercontent.com/40298250/115115356-83b59f80-9f6a-11eb-879d-8c658fce996a.png)

**Comment by harshal311989** [comment] 2021-04-20 12:13
@Cnilton Render your textinput inside Modal then quickly open close modal with textinput at that time you will face issue on that . 

```
<Modal
                visible={isModalVisible}
                transparent
                animationType={'slide'}
            >
                <FloatingLabelInput
               label={textTranslation.shippingAddress.FLATNAME}
               value={flateName}
              onChangeText={(value) => {
                 this.setState({ flateName: value });
               }}
            labelStyles={{
            fontFamily: globals.ProximaNovaRegular,
           color: colors.darkWarmGrey,
           }}
         />
/>  
</View>
```

**Comment by harshal311989** [comment] 2021-04-21 04:52
@Cnilton any updates on this?

**Comment by Cnilton** [comment] 2021-04-21 12:15
@harshal311989, I'm sorry but I still couldn't reproduce the issue. Please see video and image below:

![untitled2](https://user-images.githubusercontent.com/40298250/115551855-0350b080-a282-11eb-8b27-7d360205c66e.gif)
![Sem título](https://user-images.githubusercontent.com/40298250/115551893-0b105500-a282-11eb-87de-7ab53845d214.png)

**Comment by harshal311989** [comment] 2021-04-22 04:59
@Cnilton add value pre defined in textfiled like below then run I am sure you can able to reproduce Check my video file for your refernce 

https://user-images.githubusercontent.com/75067288/115658049-a45c6b80-a355-11eb-9b15-21908fbbe2e3.mp4


`render(){
const {isModalVisible} = this.state;
return(
       <TouchableOpacity onPress={()=>{this.setState({isModalVisible: true})}}
            <Text>{'Open Modal}</Text>
       </TouchableOpacity>

      
<Modal
                visible={isModalVisible}
                transparent
                animationType={'slide'}
            >
                <FloatingLabelInput
               label={'FlatName'}
               value={"Hello I am React Native Developer"}
              onChangeText={(value) => {
                 this.setState({ flateName: value });
               }}
            labelStyles={{
            fontFamily: globals.ProximaNovaRegular,
           color: colors.darkWarmGrey,
           }}
         />
         <TouchableOpacity onPress={()=>{this.setState({isModalVisible: false})}}
            <Text>{'Close Modal}</Text>
       </TouchableOpacity>
/>  
)}`

**Comment by Cnilton** [comment] 2021-04-22 22:54
@harshal311989, I could reproduce this issue now. Soon I'll release a new version to fix this!

**Comment by harshal311989** [comment] 2021-04-23 07:03
ok @Cnilton

**Comment by Cnilton** [comment] 2021-04-23 16:59
@harshal311989, can you please try the newest version 1.3.7?  After fixing this issue with that version, I couldn't reproduce the issue anymore.

**Comment by harshal311989** [comment] 2021-04-26 10:15
OK @Cnilton let me try that version

**Comment by harshal311989** [comment] 2021-04-27 06:11
@Cnilton I checked in 1.3.7 version it is resolved now. Thanks for your support

**Comment by Cnilton** [comment] 2021-04-27 12:08
@harshal311989, that's great! Thanks for the quick response, I'll be closing this then.

**Closed by Cnilton** 2021-04-27 12:08 UTC
